name: CI

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Test
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install
      - run: yarn nx test api --codeCoverage

      - uses: cicirello/jacoco-badge-generator@v2
        name: Generate Badge
        with:
          jacoco-csv-file: coverage/apps/api/report.xml
          badges-directory: coverage/apps/api/badges

      - uses: JamesIves/github-pages-deploy-action@v4
        name: Publish to pages
        with:
          folder: coverage/apps