name: CI

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Test
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install
      - run: yarn test:ci

      - name: Generate Badge
        uses: nrwl/nx-set-shas@v3
      - run: yarn add make-coverage-badge
      - run: yarn make-coverage-badge
        