name: CI

on:
  push:
    branches:
      - actions
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Test
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install
      - run: yarn nx test api --codeCoverage

      - name: Generate Badge
      - run: yarn install make-coverage-badge
      - run: yarn make-coverage-badge

      - name: Publish to pages
        